### ISSUE TITLE
Tracker url is still default

### ISSUE THREAD

**Issue by Naxanria** [zmatez/wildnature#12]
The tracker url for update check is still the default http://myurl.me/
`[24Nov2019 18:56:25.413] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [wildnature] Starting version check at http://myurl.me/`

**Comment by zmatez** [comment]
We're working on a WildNature website. Then we will change the Update Checker url for sure.

**Comment by Naxanria** [comment]
As a potential suggestion till that time, comment out the tracker link in the `mods.toml`? Then it wont show up with an error in the log :)

**Comment by zmatez** [comment]
Added update checker link in v2.1.0
