### ISSUE TITLE
Config stone variants

### ISSUE THREAD

**Issue by Sunekaer** [zmatez/wildnature#13]
Currently all the stone variant is taking over the world and causing there to be nearly no vanilla stones/ores and other modded stones/ores

Please add configs for:
Disabling each stone variant 
Min and max height, cluster size and count ( how many clusters there can be in a chunk) for each stone
Dimension and biome whitelist/blacklist for each stone

**Comment by zmatez** [comment]
Done.
Effects in WN 2.1.0
