### ISSUE TITLE
Disabled stone not removed in JEI

### ISSUE THREAD

**Issue by Sunekaer** [zmatez/wildnature#17]
When changing setting "generator.rocks.all" to false or "generator.rocks.sedimentary" to false the blocks don't get removed from JEI

**Comment by zmatez** [comment]
This option just removes generation stones on world, it isn't deleting items and blocks from inventory.

**Comment by Sunekaer** [comment]
Okay, could you add config to disable them? or give me a list of what is "sedimentary" then ill remove them myself with scripts
