### ISSUE TITLE
Config to disable "Using WildNature 2.1.0 without WildNature World Generator"

### ISSUE THREAD

**Issue by Sunekaer** [zmatez/wildnature#18]
This message doesnt respect "message_on_join" or "effect_on_join" setting

**Comment by Sunekaer** [comment]
The config files is generating wrong or something
So you have a config file in the serverconfig folder but you also have on in config/wildnature and the contain the same settings, and the mod reads from both?
I would recommend just changing over to use common config

**Comment by Sunekaer** [comment]
also 
So with 1.14, forge created a folder called defaultconfigs, that modpacks makers should use to ship changed configs with, so the pack gets the right client, common and server config.
It takes the client and common files and puts them in the config folder and server files in the serverconfig folder.
So if I put wildnature-config.toml in defaultconfigs it wont know where to put that file and my changed configs wont work.

**Comment by Barerock** [comment]
Okay, I get this a well. Weird problem. But what does it mean? Is something actually wrong or not?

**Comment by zmatez** [comment]
Fixed
