### ISSUE TITLE
Missing recipes

### ISSUE THREAD

**Issue by Sunekaer** [zmatez/wildnature#19]
All rocks has stairs, slabs, brick, mossy, wall, trapdoor, fence versions and more but none of it has recipes

**Comment by zmatez** [comment]
Really? I have tested it and everything worked. Hmm maybe only on basalt.. check the basalt. If I will back to home I will check it

**Comment by Sunekaer** [comment]
None of the stones has a use when I look in JEI

**Comment by zmatez** [comment]
Weird, but all recipes for stone works. Maybe JEI just does not recognise it.

**Comment by Sunekaer** [comment]
Hmm could you show me some recipes that works for you, and ill see if they do for me

**Comment by zmatez** [comment]
Same recipes as minecraft ones. Smelt cobble to rock, make bricks, or just insert bricks/rock/polished to stonecutter

**Comment by Sunekaer** [comment]
![image](https://user-images.githubusercontent.com/18720460/70374558-28928800-18f4-11ea-8952-6cc777c3dc23.png)
![image](https://user-images.githubusercontent.com/18720460/70374572-45c75680-18f4-11ea-81af-d291b31ccaa8.png)

**Comment by Sunekaer** [comment]
Same for other stone types

**Comment by zmatez** [comment]
lol i've tested it hour ago. Try without JEI

**Comment by Sunekaer** [comment]
Sure, dont see how JEI should break recipes..
But same issue

**Comment by Sunekaer** [comment]
Found issue.

**Comment by zmatez** [comment]
fixed?

**Comment by Sunekaer** [comment]
Yeah, one of my scripts was removing the recipes... and i didnt knew that it was doing that :D
