### ISSUE TITLE
the Bulls drop chicken?

### ISSUE THREAD

**Issue by WitherKing20** [zmatez/wildnature#2]
Why are the Bulls Dropping Chicken instead of beef?

**Comment by zmatez** [comment]
Yeah, but the 1.12.2 version is discontiuned. Sorry

**Comment by Oddlybird** [comment]
It's out of date now, but -- I've found the bulls in 1.12.2 are also dropping male duck feathers.  If anyone reports this happening in a modern version, doublecheck that the bulls are using the right loot table.
