### ISSUE TITLE
More config for generation

### ISSUE THREAD

**Issue by Sunekaer** [zmatez/wildnature#20]
Could you add config like this for each stone?

	#Maximal height for basalt pocket generation 
	#Range: 0 ~ 255
	basaltMaxHeight =

	#Size of basalt pockets 
	#Range: 0 ~ 100
	basaltSize = 

	#Generate basalt in the world [true / false]
	basaltGeneration = 

	#Minimal height for basalt pocket generation
	#Range: 0 ~ 255
	basaltMinHeight = 

	#Chances of basalt pocket being generated
	#Range: 0 ~ 100
	basaltChance =

**Comment by AvrgDerk** [comment]
This would be really useful for compatibility with quark.

**Comment by zmatez** [comment]
done
