### ISSUE TITLE
Villages in Polders do not generate at the correct height

### ISSUE THREAD

**Issue by Naxanria** [zmatez/wildnature#22]
![image](https://user-images.githubusercontent.com/3246224/70375631-34844700-1900-11ea-8d15-42dcc68c8a36.png)

**Comment by DoragonKeiyou** [comment]
Notice that issue myself.  The whole biome is generating lower than it should, about 20 blocks lower than sea level.
![image](https://user-images.githubusercontent.com/9502203/70768184-a823bb00-1d29-11ea-913f-44636ac6b624.png)

**Comment by Naxanria** [comment]
Polders are (flat) areas that are below sea level, drained of water. So that is correct. It is the village spawn height not following along.

**Comment by zmatez** [comment]
It seems that the villages there have to be deleted, because in minecraft code there is a lock to not spawn villages lower than the sea level.

**Comment by zmatez** [comment]
Removed
