### ISSUE TITLE
Mod conflict with Gobber ring of growth.

### ISSUE THREAD

**Issue by ProsperCraft** [zmatez/wildnature#24]
https://github.com/kwpugh/gobber/issues/19

**Comment by kwpugh** [comment]
Hi,

I am the author of Gobber.  Can you share your source code so I can see how your mod works and figure out what is going wrong with the Ring of the Farmer?

Thank you

**Comment by zmatez** [comment]
@kwpugh which part you want? Grass block code?

**Comment by kwpugh** [comment]
Not entirely sure.   The lockup reported was related to the GrassBase class but I don’t know where that will lead me.

Can you just publish the mod on GitHub?   That would be easiest.

**Comment by kwpugh** [comment]
BTW: are you implementing IGrowable for your grass block?

**Comment by Naxanria** [comment]
It extends `GrassBlock`, so it is indeed an `IGrowable`. 
Looking at the code of your ring of the farmer, instead of excluding all those blocks, maybe check if it is an instance of `SaplingBlock` or `CropsBlock` before trying to grow?

**Comment by kwpugh** [comment]
Great and simple suggestions, thank you.

Please see version 116 of Gobber, this appears to correct the problem.

Please test and confirm.

**Comment by kwpugh** [comment]
https://www.curseforge.com/minecraft/mc-mods/gobber/files/2844532

**Comment by Naxanria** [comment]
Awesome! :D
