### ISSUE TITLE
Some config options have no effect

### ISSUE THREAD

**Issue by Benji-Collins** [zmatez/wildnature#25]
The 'message_on_join' and 'blacklist' config options seem to have no effect in-game. It's possible that the same is true for some of the other options.

The config file itself works however, as setting '[generator.rocks] all' to false has removed all the WildNature rocks from my test worlds. Similarly, the 'effect_on_join' setting works as expected. The log shows that the config file is loaded correctly.

This was initially tested with Minecraft 1.14, WildNature v2.1 and Forge 28.1.64. I also experienced this same issue with Forge 28.1.87 (the recommended version) and Forge 28.1.107 (latest at time of writing).

**Comment by zmatez** [comment]
Fixed
