### ISSUE TITLE
Animals not spawning

### ISSUE THREAD

**Issue by Barerock** [zmatez/wildnature#28]
Latest 2.1 build for 1.14
Forge 28.1.106
Animals don't spawn on a server or single player. No other info gathered.

**Comment by zmatez** [comment]
Animals from which mod?

**Comment by Barerock** [comment]
The wildnature 2.1 mod? Are there multiple mods to download? The Curseforge page is very confusing on that regard, since it advertises mobs as well as world gen.

**Comment by zmatez** [comment]
But them just does not exist. We haven't added them yet. But we're planning. More and more ;)

**Comment by Barerock** [comment]
You might want to emphasize that with more than asterisks on the Curseforge page because I had absolutely no idea that's what that meant. And some people can't be bothered to clutter their discord with miscellaneous channels.
