### ISSUE TITLE
REQUEST: Could you add a Forge tag for your stones

### ISSUE THREAD

**Issue by kwpugh** [zmatez/wildnature#29]
Hi,

I have modded items that select blocks based on their Forge tag of STONE.  Other mod authors have added these for cross mod compatibility.

Would you mind adding them please for your slate, marble, conglomerate, etc?

Here is link to how EmbellishCraft did it:
https://github.com/MapperTV/embellishcraft/blob/master/src/main/resources/data/forge/tags/blocks/stone.json

Thank you,

Kevin

**Comment by zmatez** [comment]
Done

**Comment by kwpugh** [comment]
Thank you very much.
