### ISSUE TITLE
Generating a normal vanilla world with Wild Nature present causes a crash in placing plants (1.14.4)

### ISSUE THREAD

**Issue by McJty** [zmatez/wildnature#33]
I made a normal world (no Wild Nature world type) and immediatelly crashed in your PlantFeature class at this line:

                if (worldIn.isAirBlock(blockpos) && state.isValidPosition(worldIn, blockpos)) {

The problem is that 'state' is null because this line returns null:

        BlockState state = MathCalc.getWeighBlock(this.list);

And the reason that returns null is that the list of possible plants is empty. This does not happen if you select Wild Nature as worldtype

**Comment by zmatez** [comment]
Thanks, problem solved.
Btw there is already a try/catch block, idk why it crashes

**Comment by McJty** [comment]
Oh, It was probably because I was debugging with exception breakpoints enabled that I noticed those exceptions. In a real situation there were probably not really a problem. BTW, maybe not a good idea to just try/catch exceptions without logging or anything :-)
