### ISSUE TITLE
[2.1.1] Some pine leaves have no texture soon after generating (possibly as they decay)

### ISSUE THREAD

**Issue by Benji-Collins** [zmatez/wildnature#34]
On 2.1.1 pine leaves (on trees) will sometimes show as having no texture, possibly as they reach a certain point of decay.

![2020-01-03_12 45 06](https://user-images.githubusercontent.com/34997963/71705219-78e70200-2e2e-11ea-9d0f-4fa04d259147.png)
![2020-01-03_12 18 53](https://user-images.githubusercontent.com/34997963/71705224-83a19700-2e2e-11ea-88d0-88320bd36575.png)

**Comment by zmatez** [comment]
Fixed
