### ISSUE TITLE
[2.1.1] [Possibly intended] Mangrove branches spawning in water aren't waterlogged

### ISSUE THREAD

**Issue by Benji-Collins** [zmatez/wildnature#35]
I'm not sure if this is intended, or if it would even be possible, but having the mangrove branches that spawn in water be waterlogged would be cool. Before and after pic:
![2020-01-03_11 38 07](https://user-images.githubusercontent.com/34997963/71705301-d11e0400-2e2e-11ea-86e4-9f888cd3c953.png)
![2020-01-03_11 38 15](https://user-images.githubusercontent.com/34997963/71705302-d24f3100-2e2e-11ea-81d8-5cbeb751930a.png)

**Comment by zmatez** [comment]
Fixed
