### ISSUE TITLE
Farmlands biome has sharp border with most other biomes

### ISSUE THREAD

**Issue by Benji-Collins** [zmatez/wildnature#36]
A side effect of the farmlands biome being completely flat is that it has sharp, cliff-like edges with many other biomes, as shown below. 
![2020-01-03_11 42 36](https://user-images.githubusercontent.com/34997963/71705354-37a32200-2e2f-11ea-8a9a-a643050cfb11.png)

**Comment by zmatez** [comment]
Fixed
Removed super flat farmlands feature, BUT added another cool thing
![2020-01-03_12 51 11](https://user-images.githubusercontent.com/43961846/71722063-d62b8500-2e27-11ea-9d8b-f875722dae63.png)
