### ISSUE TITLE
No config file for version 1.2 (mc 1.12.2)

### ISSUE THREAD

**Issue by katubug** [zmatez/wildnature#4]
Hi! I have been trying out your mod, and I wanted to see if I could disable any parts of it (such as the replaced vanilla animals and stuff) via the config - but I actually can't find any config file at all. Is there one, and if so, what is it called?

Thanks for your time!

**Comment by zmatez** [comment]
Sorry, but the 1.12.2 version is discontinued. Config is added to 1.14.4 (v2.0.8)
