### ISSUE TITLE
Missing Snowy Grass Texture

### ISSUE THREAD

**Issue by WenXin20** [zmatez/wildnature#41]
`Minecraft v1.14.4`
`WildNature v2.1.3`

Several grass blocks seem to be missing the snowy texture when snow is placed on top.
- Tropical Grass will display a missing texture.
- Overgrown Stone will have a strange green tint on it.
- Brown Mycelium and Podzol doesn't change it's texture at all.

**Comment by zmatez** [comment]
fixed
