### ISSUE TITLE
1.14.4 Broken Textures & Lang

### ISSUE THREAD

**Issue by lactoseintolerantnihilism** [zmatez/wildnature#46]
I've been making a texture pack to make Wild Nature (1.14 version) fit with Quadral and in doing so I've noticed a few things:
Snowy versions of your grass are broken. Overgrown stone's side snow texture is just the normal one but green, tropical grass' is a missing texture, brown podzol and mycelium have no change.
![2020-02-01_17 00 32](https://user-images.githubusercontent.com/49765589/73596007-422c0680-4516-11ea-83ae-9a9ba06e5d21.png)
![2020-02-01_17 08 07](https://user-images.githubusercontent.com/49765589/73596008-422c0680-4516-11ea-9828-f43033cfa439.png)

The apple sign has no translation key and so displays as 'block.wildnature.apple_sign'. Tropical dirt is called Mold Dirt. Copper and Tin ores are called 'Copper Block' and 'Tin Block' respectively.
![composite](https://user-images.githubusercontent.com/49765589/73596103-355be280-4517-11ea-88da-3284668d352e.png)

These aren't exactly big or important but I thought I'd bring them to your attention :)

**Comment by zmatez** [comment]
Thanks for reporting, issues fixed ;)
