### ISSUE TITLE
Duplicate Blue Dye Recipe

### ISSUE THREAD

**Issue by MeinKraft** [zmatez/wildnature#51]
WildNature 2.1.4
Minecraft 1.14.4

I noticed the blue_dye2 and blue_dye4 recipes are exactly the same

**Comment by zmatez** [comment]
oh i see, thanks :)

**Comment by MeinKraft** [comment]
also white_dye5 and white_dye7

**Comment by MeinKraft** [comment]
also orange_azalea does not have an orange dye recipe
