### ISSUE TITLE
I might be stupid

### ISSUE THREAD

**Issue by hanming2752** [zmatez/wildnature#55]
Hello!
I was trying to download the mod but my computer won't download it properly. It downloads til the point where you can right click on file when it's downloading in the down-left corner where the text "open when the download is ready" button shows up. Here it's where it als goes wrong. My computer 
has the virus protection (so it might be that or its google, cuz when you press "why" or something like that its come to google) and it's thinks that the file is some sort of virus. I have file with all the other files in my computer map but i can't drop it into minecraft so i can get the biome. It also might be that I hav the 1.15 someting version of minecraft and you wrote that you need 1.12

Thanks on before hand :)

**Comment by zmatez** [comment]
Hi,
could you send me a screenshot of it?
thanks

pt., 13 mar 2020 o 23:53 hanming2752 <notifications@github.com> napisał(a):

**Comment by hanming2752** [comment]
![2020-03-14 (13)](https://user-images.githubusercontent.com/62160147/76685364-541fbf80-6613-11ea-925e-363316f78ab9.png)
I download it for here don't know if that's right or so

![2020-03-14 (15)](https://user-images.githubusercontent.com/62160147/76685367-597d0a00-6613-11ea-8d2f-98617caa7ab2.png)

"behåll" = keep "kasta = throw away

![2020-03-14 (17)](https://user-images.githubusercontent.com/62160147/76685374-626ddb80-6613-11ea-9193-e16b0c6fcfdd.png)

"öppna när nedladdningen är klar" = open when the download is ready. 
here it get to 17,7 mb but it never opens. I don't know why. I only use the "open when done" so I know it's ready.  

![2020-03-14 (18)](https://user-images.githubusercontent.com/62160147/76685377-6863bc80-6613-11ea-91dc-b74ce3e2deb8.png)

translation: 
This file is not associated with an app to perform the action. Install an app or create a association on the side to options for standard apps is there's already an app installed

![2020-03-14 (20)](https://user-images.githubusercontent.com/62160147/76685384-6f8aca80-6613-11ea-897e-bdb006925038.png)

It land (the first file on the list) here and i moved it to the minecraft app with the "versions" just to see if that would help not that i belied it. It didn't of course help at all but worth a try.

thanks for the help, really appreciate it. I'm new to download mod and other stuff. sorry to bother you.

**Comment by zmatez** [comment]
Please watch basic mod installation tutorial. Everything is fine, just that
isn't executable file. You have to firstly install minecraft forge, then
search in windows %appdata% go to roaming, .minecraft, mods and then put
there that file.

Sob., 14 mar 2020, 17:04 użytkownik hanming2752 <notifications@github.com>
napisał:

**Comment by hanming2752** [comment]
Thank you so much. I saw someone with the forge but didn't know if that was required for this mod to.
thanks again
