### ISSUE TITLE
After the newest update, biomes are HUGE

### ISSUE THREAD

**Issue by Deservedx** [zmatez/wildnature#56]
Intentional or not? Each time I create a new world, the biome I spawn in is simply huge. I didn't find the "limits" but, by using the /tp command, the biome would be the same no matter what coordinates I tried (I even tried 20000 y 20000 without any success).

**Comment by zmatez** [comment]
Go to mod config (wildnature-common) and change biome size from 6 to 4

**Comment by Deservedx** [comment]
> Go to mod config (wildnature-common) and change biome size from 6 to 4

Thank you, that fixed it. It is still weird that the default was 6...
Also, I love all the new additions!
