### ISSUE TITLE
Mold Grass Block is a cellular automaton

### ISSUE THREAD

**Issue by Epic312** [zmatez/wildnature#57]
I went to a Farmlands biome and...well, the mold grass block isn't really behaving as intended:
![2020-03-18_17 22 10](https://user-images.githubusercontent.com/18506935/77016590-b3e0d800-693d-11ea-9f21-fa44d82658fc.png)
This isn't static generation or anything - the biome generates naturally, the grass blocks just act like a cellular automaton and are ever-expanding, gradually attempting to consume the world.
**Steps to reproduce:**
1. Install the latest version of WildNature.
2. Place a mold grass block or go to a Farmlands biome.
3. Enjoy

**Comment by zmatez** [comment]
fixed in 2.1.6.4
