### ISSUE TITLE
[Improvement] Deep Bowl recipe

### ISSUE THREAD

**Issue by fhavio** [zmatez/wildnature#61]
Hello,
I have been playing in 1.14.4 with WildNature mod, and the deep bowl recipe is the same as for boats.
Would help you to fix it and share again.

Thanks and thank you for you job,
BR

**Comment by Mystravil** [comment]
i'm having the same issue.

**Comment by Zoe-twilight** [comment]
Same

**Comment by Qooai** [comment]
same

**Comment by zmatez** [comment]
Fixed in 2.1.6.5 (not public, server modpack contains it)
