### ISSUE TITLE
My Server is sometimes crashing while generating new Chunks

### ISSUE THREAD

**Issue by Willibaldgamer** [zmatez/wildnature#62]
Hi 
i updated my bukkit 1.14.4 Creative Server to a little modpack. I copied the map and deleted some far a way chunks with world edit, so far everything worked fine but sometimes (i know around 3-4 places where this happens) the Server crashes while generating the chunk. I tried to delete and regenerate this chunks but still crashes with the message java.lang.StackOverflowError

Update: I disabled all other mods generated a new map and generated chunks, after flying 16k chunks same issure, server crashing. And I was able to narrow it down further. (So far) It only happened at the biome "Snowy Giant Coniferous Forest"
Btw i tried the version 2.1.4 and 2.1.6.1
[Server Console Crash Map Generation.txt](https://github.com/zmatez/wildnature/files/4422239/Server.Console.Crash.Map.Generation.txt)

Pls help thanks 
Ps what is the Biome name in the "code", that i can blacklist it in the generation setting?
Besides that great mod

**Comment by Willibaldgamer** [comment]
Bzw i tested all other mods and only removed the Wildnature and it worked to (i tested 40k chunks without crash)

**Comment by McKitten** [comment]
My loading of the r.6.-4.mca region (crashed before, reset pos (nbtedit) and deleted entire chunk to enter it later and have the same chunk crash) https://pastebin.com/qLUhgwp1

The following/most recent reboot https://pastebin.com/8ut0XxR7 (believe this is less useful but just in case)

**Comment by zmatez** [comment]
That is already fixed in 2.1.6.5 ;)
