### ISSUE TITLE
Perennial pink and violet blockstates path typo

### ISSUE THREAD

**Issue by Areolata7** [zmatez/wildnature#65]
In 2.1.6.4 for mc1.14:

Blockstates file for perennial_pink flower is wrong so the flower was not showing texture in game I have been messing with it for some time and finally found the error and fixed it for myself.

In the blockstates json file the path is incorrectly listed as:

"wildnature:block/perennial_flower_pink"
"wildnature:block/perennial_flower_pink_flowering",

instead of: 

"wildnature:block/perennial_pink"
"wildnature:block/perennial_pink_flowering"

The extra "flower" in the middle needs to be removed. 

It is only this way in the blockstates json, and is not wrong in either of the model json.
Also the perennial_violet flowers have the same exact issue. 
The perennial_blue flower is fully functional. 

Please fix.

**Comment by zmatez** [comment]
Thank you! Fixed
