### ISSUE TITLE
1.12.2 crashing 

### ISSUE THREAD

**Issue by Pandzixs** [zmatez/wildnature#66]
When i start playing in 1 12 2 with wild nature  minecraft crashing
can u fix this problem? 
someone have this problem too? someone fixedthis?

**Comment by zmatez** [comment]
Try running plain wildnature. In 1.12.2 theres one problem with biomes - max 256 can be added. So if you have another biome mods installed, it will not work and your game will crash.

I suggest moving onto 1.14.4, WildNature there contains MOORE epic features, also 1.12.2 is no longer supported(by us and by forge btw)
