### ISSUE TITLE
Eating certain foods causes a crash

### ISSUE THREAD

**Issue by thisisnotavailable3** [zmatez/wildnature#79]
When eating cheese, toast, sliced bread, or any crafted foods besides cake and tea, a crash occurs:
[crash-2020-05-23_20.14.34-server copy.txt](https://github.com/zmatez/wildnature/files/4688360/crash-2020-05-23_20.14.34-server.copy.txt)

**Comment by zmatez** [comment]
Yeah, know that, still thanks for reporting. It will be fixed soon in 2.1.7
