### ISSUE TITLE
Crash on placing tree seeds on mod grass blocks

### ISSUE THREAD

**Issue by Nikipedia** [zmatez/wildnature#98]
MC version 1.15.2, Forge version 31.2.47, WildNature 3.0

To reproduce: Server immediately crashes when placing any tree seeds (tried with: Larch Cone, Pine Cone, Ebony Seed) on any mod-pack grass block, happens in survival+creative, no matter how item was obtained. 
Mod flowers can be placed on the mod grass blocks, cones can be placed on standard minecraft grass and dirt without crash.
This crash does not seem to occur in singleplayer.

Pastebin: https://pastebin.com/GWgzBx8N

**Comment by zmatez** [comment]
Yeah, I know about it. I'm working on a bugfix. Now just avoid placing seeds :)
