### ISSUE TITLE
Crash when launching game 1.15.2

### ISSUE THREAD

**Issue by lartts** [zmatez/wildnature#99]
Log:
[latest.log](https://github.com/zmatez/wildnature/files/6250082/latest.log)

Report:
[crash-2021-04-02_22.04.31-client.txt](https://github.com/zmatez/wildnature/files/6250085/crash-2021-04-02_22.04.31-client.txt)

**Comment by zmatez** [comment]
Hello! Please update your forge to the **latest** one, not recommended (it should be over 31.2.45). This will fix your problem.
